# Generated by Django 3.2.2 on 2022-03-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('discription', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
