# Generated by Django 3.2.2 on 2022-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0002_auto_20220323_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sliderImage',
            field=models.ImageField(null=True, upload_to='uploads/slider/'),
        ),
    ]
