# Generated by Django 3.2.2 on 2022-03-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0003_product_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/slider/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='sliderImage',
        ),
    ]
