# Generated by Django 3.2.2 on 2022-03-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0004_auto_20220324_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(null=True, upload_to='static/images/slider'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
