# Generated by Django 3.2.2 on 2022-03-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0009_auto_20220327_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
    ]
