# Generated by Django 3.2.2 on 2022-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0010_rename_image_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
