# Generated by Django 3.2.2 on 2022-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0011_product_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
