# Generated by Django 3.2.2 on 2022-05-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0012_auto_20220409_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.IntegerField(default='000', max_length=13),
        ),
    ]
