# Generated by Django 3.2.2 on 2022-05-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0013_customer_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='number',
            new_name='Contact_number',
        ),
    ]
