# Generated by Django 3.2.2 on 2022-05-14 07:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0015_alter_customer_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
