# Generated by Django 3.2.2 on 2022-05-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0018_auto_20220521_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='digits',
        ),
        migrations.AddField(
            model_name='practice',
            name='discription',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='imagee',
            field=models.ImageField(default='', upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='practice',
            name='title',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
