# Generated by Django 3.2.2 on 2022-05-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0021_delivery_boy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='delivery_boy',
            new_name='Deliveryboy',
        ),
    ]
