# Generated by Django 3.2.2 on 2022-05-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0022_rename_delivery_boy_deliveryboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='stat',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='duty', max_length=50),
        ),
    ]
