# Generated by Django 3.2.2 on 2022-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0023_deliveryboy_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='emaill',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='stat',
            field=models.CharField(choices=[('duty', 'duty'), ('took off', 'took off'), ('free', 'free')], default='duty', max_length=50),
        ),
    ]
